[tool.black]
line-length = 79
py36 = true

[tool.poetry]
name = "tvdb_api_client"
version = "0.1.5"
description = "A python client for TVDB rest API"
authors = ["spapanik <spapanik21@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

requests = "^2.0"

[tool.poetry.dev-dependencies]
black = "^18.0"
