[tool.black]
line-length = 79
py36 = true

[tool.poetry]
name = "pygatherer"
version = "0.0.1"
description = "A python client for TVDB rest API"
authors = ["Steph Papanik <spapanik21@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

requests = "^2.0"

[tool.poetry.dev-dependencies]
black = "^18.0"
pytest = "^3.0"
